"""remove_user_token

Revision ID: 1598f8581815
Revises: fcae5e791013
Create Date: 2025-12-31 16:42:17.618224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1598f8581815'
down_revision = 'fcae5e791013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###

