"""add_users_table

Revision ID: fcae5e791013
Revises: da130b95b66f
Create Date: 2025-12-30 18:18:08.398076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcae5e791013'
down_revision = 'da130b95b66f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

